apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - redis-deployment.yaml
  - postgres-deployment.yaml

patches:
  - path:  patches/configmap.yaml
  - path:  patches/secret.yaml
