apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path:  patches/configmap.yaml
  - path:  patches/secret.yaml

replicas:
  - name: api
    count: 2
  - name: worker
    count: 2
