apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - api-hpa.yaml
  - worker-hpa.yaml

patches:
  - path:  patches/configmap.yaml
  - path:  patches/secret.yaml
  - path:  patches/api-resources.yaml
  - path:  patches/worker-resources.yaml
